-- 序列
CREATE SEQUENCE HIBERNATE_SEQUENCE INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1;

-- 创建项目表，注意：jpa默认创建的字段类型是按最大存储创建的，请根据需要修改为合理字段类型。
CREATE TABLE T_PROJECT (
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    CONFIG_JSON BLOB NULL,
    CONFIG_TEXT CLOB NULL,
    CREATE_TIME DATETIME NOT NULL,
    "CYCLE" INTEGER NOT NULL,
    INTERNAL BIT NULL,
    LAST_MODIFIED_DATE DATETIME NULL,
    NAME VARCHAR(100) NOT NULL,
    REMARKS VARCHAR(255) NULL,
    SORT BIGINT NOT NULL UNIQUE,
    STATE INTEGER NULL,
    "TYPE" VARCHAR(255) NULL
);

